API carrinho [DRAFT]
PedroAmorimG/ProjetoTraineeStruct pull request #28
Opened 2023-12-18 20:54 UTC by PedroAmorimG

API n testada ,por enquanto, n consigo userId. Provavelmente sera necessario mudar o metodo de conseguir o userId

2023-12-19 19:00 UTC, pafev requested changes

2023-12-19 19:00 UTC, pafev commented on cocinaborcelle/src/pages/user/index.tsx
> +}) satisfies GetServerSideProps;
o que você pode fazer, caso tenha tempo, é uma função de getServerSide no arquivo do userContext e exportar ela, onde nela você não replica o código de pegar session

https://nextjs.org/docs/pages/building-your-application/routing/authenticating
esse link é a sessão do next auth que fala de como implementar autenticação no pages router. Aqui ele fala que existem duas formas, chamando o usuário por client side, com uma função useUser (como fizemos), e aí todas as ações e requests referentes ao usuário também seriam client side

ou você pode exportar uma função de getServerSideProps chamada withSession, que chamaria esse usuário por client side e executaria a função que você passou como parâmetro

seria tipo:
`const getServerSideProps = withSession(( { req, res} ) => ...)`

não acho que seja tão complicado, mas demandaria mais tempo e o projeto é amanhã

2023-12-19 20:37 UTC, PedroAmorimG commented
Acho que pras paginas exclusivas de Admin seria legal aplicar verificacao com getServerSideProps porque utilizando o useContext ainda vaza um pouco da pagina enquanto a API n responde

2023-12-20 01:20 UTC, pafev requested changes

2023-12-20 01:20 UTC, pafev commented on cocinaborcelle/src/clientApi/carrinho/getCarrinho.ts
> +export type CarrinhoCompleto = { carrinho: Carrinho & Compra };
```suggestion
export type CarrinhoCompleto = {
	carrinho: Carrinho & { 
		compras: (Compra & { comida: Comida })[] 
	};
};
```

não esqueça que:
- está dando um include true pra comida também
- um carrinho tem um array de compras, no seu atributo .compras
- uma compra tem uma comida, no seu atributo .comida

para checar, é só passar o mouse por cima do que vc tá retornando lá na api do lado do servidor

2023-12-20 15:28 UTC, pafev approved these changes

2023-12-20 15:28 UTC, merged