Pagina Login e Cadastro, e componentes
PedroAmorimG/ProjetoTraineeStruct pull request #6
Opened 2023-12-05 17:52 UTC by PedroAmorimG

2023-12-08 12:39 UTC, PedroAmorimG commented
> Falta fazer o Login funcionar no chrome e LogOut de uma maneira geral.

Falta fazer o Login funcionar em navegadores diferentes do firefox

2023-12-08 14:44 UTC, pafev commented on cocinaborcelle/src/pages/_app.tsx
> +		<SessionProvider>
você precisar passar a session do usuário para o SessionProvider

2023-12-08 14:47 UTC, pafev commented on cocinaborcelle/prisma/schema.prisma
> +}
Não sei se é do padrão de credentials provider, mas utilizando provedores externos, por exemplo, teria que utilizar outras models para o usuário
```suggestion
model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? // @db.Text
  access_token      String? // @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? // @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model Usuario {
  id            String    @id @default(cuid())
  nome          String
  email         String?   @unique
  emailVerified DateTime?
  
  carrinho Carrinho?

  accounts Account[]
  sessions Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

2023-12-08 14:51 UTC, pafev commented on cocinaborcelle/src/pages/_app.tsx
> +		<SessionProvider>
```suggestion
		<SessionProvider session={session}>
```

2023-12-08 14:56 UTC, pafev commented on cocinaborcelle/src/pages/api/auth/[...nextauth].ts
> +		CredentialsProvider({
preciso saber sua resposta para isso, antes de continuar a correção

2023-12-08 14:57 UTC, PedroAmorimG commented on cocinaborcelle/prisma/schema.prisma
> +}
Pelo que eu vi a autenticação por credentials é toda pelo jwt usando next e não envolveria nada do prisma além de verificar a senha.

2023-12-08 14:59 UTC, PedroAmorimG commented on cocinaborcelle/src/pages/api/auth/[...nextauth].ts
> +		CredentialsProvider({
Acho que o Lucia Auth

2023-12-08 15:00 UTC, PedroAmorimG commented on cocinaborcelle/src/pages/_app.tsx
> +		<SessionProvider>
Tinha tirado pra tentar outra solução que não deu certo e esqueci de voltar

2023-12-08 19:29 UTC, pafev commented on cocinaborcelle/prisma/schema.prisma
> +}
é porque não salva o usuário no banco de dados né. Realmente credenciais pelo nextauth é mt ruim

2023-12-09 00:31 UTC, PedroAmorimG commented
Pagina Index.tsx foi pra testar o sistema de sessao, falta adicionar dinamica nas paginas quando ocorre algum erro de usuario. Possilvelmente, posso deixar um pagina de como pegar os dados da sessao na main pra mostrar como funciona.

2023-12-12 21:24 UTC, pafev requested changes

2023-12-12 21:24 UTC, pafev commented on cocinaborcelle/src/pages/api/cadastrar.ts
> +				providerId: "username",
```suggestion
				providerId: "email",
```

se você tá passando email em providerUserId, então o provedor é o email (isso não muda na funcionalidade da key)

2023-12-12 21:24 UTC, pafev commented on cocinaborcelle/src/pages/api/excluirConta.ts
> +	if (req.method != "POST") {
```suggestion
	if (req.method != "DELETE") {
```

Já que está excluindo uma instância do banco de dados, utilize o método http delete. Utilizar os métodos certos ajuda em depurações futuras, para quando for olhar o que deu errado no console ou em network do browser

2023-12-12 21:24 UTC, pafev commented on cocinaborcelle/src/pages/api/updateConta.ts
> +	if (req.method != "POST") {
```suggestion
	if (req.method != "PATCH") {
```

para alterar dados de uma instância do banco de dados, pode utilizar o método patch. Padronizar os métodos http com o seu contexto de uso ajuda em depurações futuras

obs.: a exceção que curto utilizar para isso é o de login de usuário, que, apesar de pegar informações do banco de dados, não é top usar get e sim post, pois os métodos que alteram algo do banco de dados possuem um nível de segurança maior, como post, put, patch, enfim

2023-12-12 21:24 UTC, pafev commented on cocinaborcelle/src/pages/index.tsx
> +					});
```suggestion
					}).catch(e => alert(e));
```

é sempre recomendado colocar algum tratamento de erro

2023-12-12 21:24 UTC, pafev commented on cocinaborcelle/src/pages/index.tsx
> +					});
```suggestion
					axios.delete("api/excluirConta").then((response) => {
						if (response.status == 200) {
							router.push("/Login");
						}
					}).catch(e => alert(e));
```

utilizando o método delete, então aí chama axios.delete

2023-12-12 21:31 UTC, pafev commented on cocinaborcelle/src/pages/api/cadastrar.ts
> +		const session = await auth.createSession({
```suggestion
		});
		
		await prisma_client.carrinho.create({data:{valor_cents: 0, usuarioId: user.userId}})
		
		const session = await auth.createSession({
```

recomendo criar o carrinho do usuário assim que criar sua conta. Aí, quando ele acessar o seu carrinho, n dará erro e será necessário apenas um show

2023-12-12 23:34 UTC, PedroAmorimG commented on cocinaborcelle/auth/lucia.ts
> +	env: "DEV",
Onde fica definido esse NODE_ENV?

2023-12-13 00:40 UTC, pafev commented on cocinaborcelle/auth/lucia.ts
> +	env: "DEV",
ele fica lá em node_modules

2023-12-13 00:44 UTC, pafev commented on cocinaborcelle/auth/lucia.ts
> +	env: "DEV",
pra entender melhor, node é um software que fornece um ambiente de execução, no caso ele possibilita a gente executar código JavaScript fora do navegador e principalmente no lado do servidor. NODE_ENV é uma variável de ambiente que refere ao modo de operação do nosso node, ele pode ser "development" (quando quer rodar sua aplicação em ambiente de desenvolvimento, sem expor pra internet), "production" (quando vc já quer realizar o deploy da aplicação, ou seja, "subir ela no ar") e "test" (o nome é autoexplicativo kkk)

2023-12-13 01:25 UTC, pafev approved these changes

2023-12-17 03:44 UTC, merged